version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - echo "Updating PATH to include user-installed packages..."
      - export PATH=$PATH:$HOME/.local/bin
  pre_build:
    commands:
      - echo "Checking PATH..."
      - echo $PATH
      - echo "Listing installed packages..."
  build:
    commands:
      - echo "Running github-to-lambda..."
      - python lambda_function.py || { echo "github-to-lambda command failed"; exit 1; }
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip . -x "*.git*" -x "*.github*" -x "buildspec.yml"
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
artifacts:
  files:
    - deployment_package.zip
